### ISSUE TITLE
Publishing with Azure Pipelines

### ISSUE THREAD

**Issue by Vulthil** [FishandRichardsonPC/yarn-plugin-az-cli-auth#2]
Hi there.

Using this plugin, my Azure DevOps pipeline can't publish to the private feed.

Do you know anything about a fix for this ?

I'm not sure it's the plugins fault.

**Comment by raffaeldp** [comment]
I have the same issue here. My CI is failing every time. 
Did you find a way to fix it since ? 

Edit : 
As a workaround, I have created a second file called docker.yarnrc.yaml without this plugin inside. The in my pipeline I replace the other one with this one : 
```
  - task: CmdLine@2
    displayName: 'Replace Yarn RC file'
    inputs:
      script: cp docker.yarnrc.yml .yarnrc.yml
```
